# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:    
   
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'SCN'
    subscriptionId: 'd6f9e502-800e-4deb-ac9d-ec29121bbb7b'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/lassehastrup/AutomaticDeployment/master/NewResourceGroup.json'
    overrideParameters: '-rgName $(rgName) -rgLocation $(rgLocation)'
    deploymentMode: 'Incremental'
    deploymentName: 'ResourceGroupDeployment'
